import { generateId } from "@lib/id";
import { relations } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  pgEnum,
  pgTable,
  pgTableCreator,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// Roles (stored as text on the Better Auth user table)
// ---------------------------------------------------------------------------

export const ORG_ROLES = ["admin", "seller", "user"] as const;
export type OrgRole = (typeof ORG_ROLES)[number];

// ---------------------------------------------------------------------------
// Multi-project schema pattern (t3 stack): every GASAK-owned table is
// prefixed so this DB can be shared with other projects. Better Auth's own
// tables below are named as its adapter expects and are left unprefixed.
// ---------------------------------------------------------------------------

export const createTable = pgTableCreator((name) => `gasak_${name}`);

// ---------------------------------------------------------------------------
// Better Auth tables (generated by @better-auth/cli)
// ---------------------------------------------------------------------------

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
  role: text("role"),
  banned: boolean("banned").default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    impersonatedBy: text("impersonated_by"),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

// ---------------------------------------------------------------------------
// Domain enums
// ---------------------------------------------------------------------------

export const laneEnum = pgEnum("lane", [
  "exp",
  "jungle",
  "mid",
  "gold",
  "roam",
]);

export const squadRoleEnum = pgEnum("squad_role", [
  "leader",
  "coach",
  "player",
  "reserve",
]);

export const applicationStatusEnum = pgEnum("application_status", [
  "applied",
  "under_review",
  "trial",
  "accepted",
  "rejected",
]);

export const eventTypeEnum = pgEnum("event_type", [
  "practice",
  "tournament",
  "meeting",
  "scrim",
]);

export const productCategoryEnum = pgEnum("product_category", [
  "diamonds",
  "weekly_pass",
  "joki",
  "coaching",
]);

export const orderStatusEnum = pgEnum("order_status", [
  "pending",
  "waiting_payment",
  "paid",
  "processing",
  "completed",
  "cancelled",
]);

export const paymentMethodEnum = pgEnum("payment_method", [
  "duitnow_qr",
  "bank_transfer",
  "fpx",
  "billplz",
]);

// ---------------------------------------------------------------------------
// Domain tables
// ---------------------------------------------------------------------------

export const playerProfiles = createTable("player_profiles", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  fullName: text("full_name"),
  nickname: text("nickname"),
  ign: text("ign"),
  mlbbId: text("mlbb_id"),
  serverId: text("server_id"),
  phone: text("phone"),
  preferredLane: laneEnum("preferred_lane"),
  currentRank: text("current_rank"),
  peakRank: text("peak_rank"),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const squads = createTable("squads", {
  id: uuid("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  name: text("name").notNull(),
  description: text("description"),
  logoUrl: text("logo_url"),
  bannerUrl: text("banner_url"),
  // Optional hex accent color (e.g. #d97b16); falls back to the app-wide gold
  accentColor: text("accent_color"),
  archived: boolean("archived").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const squadMembers = createTable(
  "squad_members",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    squadId: uuid("squad_id")
      .notNull()
      .references(() => squads.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    squadRole: squadRoleEnum("squad_role").notNull().default("player"),
    joinedAt: timestamp("joined_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("gasak_squad_members_squad_user_idx").on(t.squadId, t.userId),
  ],
);

export const applications = createTable("applications", {
  id: uuid("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  fullName: text("full_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  ign: text("ign").notNull(),
  mlbbId: text("mlbb_id").notNull(),
  serverId: text("server_id").notNull(),
  currentRank: text("current_rank").notNull(),
  preferredLane: laneEnum("preferred_lane").notNull(),
  heroPool: text("hero_pool").notNull(),
  previousTeam: text("previous_team"),
  introduction: text("introduction").notNull(),
  status: applicationStatusEnum("status").notNull().default("applied"),
  assignedLeaderId: text("assigned_leader_id").references(() => user.id, {
    onDelete: "set null",
  }),
  reviewNotes: text("review_notes"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const events = createTable(
  "events",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    title: text("title").notNull(),
    description: text("description"),
    type: eventTypeEnum("type").notNull().default("practice"),
    startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
    endsAt: timestamp("ends_at", { withTimezone: true }),
    location: text("location"),
    // null squadId means an org-wide event
    squadId: uuid("squad_id").references(() => squads.id, {
      onDelete: "cascade",
    }),
    createdBy: text("created_by").references(() => user.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("gasak_events_squad_idx").on(t.squadId)],
);

export const tournaments = createTable(
  "tournaments",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    name: text("name").notNull(),
    organizer: text("organizer"),
    date: timestamp("date", { withTimezone: true }).notNull(),
    prize: text("prize"),
    opponent: text("opponent"),
    result: text("result"),
    mvp: text("mvp"),
    screenshotUrl: text("screenshot_url"),
    squadId: uuid("squad_id").references(() => squads.id, {
      onDelete: "cascade",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("gasak_tournaments_squad_idx").on(t.squadId)],
);

export const scrims = createTable(
  "scrims",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    squadId: uuid("squad_id")
      .notNull()
      .references(() => squads.id, { onDelete: "cascade" }),
    opponent: text("opponent").notNull(),
    date: timestamp("date", { withTimezone: true }).notNull(),
    result: text("result"),
    notes: text("notes"),
    replayLink: text("replay_link"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("gasak_scrims_squad_idx").on(t.squadId)],
);

export const announcements = createTable(
  "announcements",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    title: text("title").notNull(),
    content: text("content").notNull(),
    // null squadId means a global announcement
    squadId: uuid("squad_id").references(() => squads.id, {
      onDelete: "cascade",
    }),
    authorId: text("author_id").references(() => user.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("gasak_announcements_squad_idx").on(t.squadId)],
);

export const announcementReads = createTable(
  "announcement_reads",
  {
    announcementId: uuid("announcement_id")
      .notNull()
      .references(() => announcements.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    readAt: timestamp("read_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("gasak_announcement_reads_announcement_user_idx").on(
      t.announcementId,
      t.userId,
    ),
  ],
);

export const authSlides = createTable("auth_slides", {
  id: uuid("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  title: text("title").notNull(),
  description: text("description").notNull(),
  eyebrow: text("eyebrow").notNull().default("GASAK Management"),
  imageUrl: text("image_url").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const activityLogs = createTable(
  "activity_logs",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    actorId: text("actor_id").references(() => user.id, {
      onDelete: "set null",
    }),
    actorName: text("actor_name"),
    actorEmail: text("actor_email"),
    actorRole: text("actor_role"),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id"),
    description: text("description").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("gasak_activity_logs_actor_idx").on(t.actorId),
    index("gasak_activity_logs_entity_idx").on(t.entityType, t.entityId),
    index("gasak_activity_logs_created_at_idx").on(t.createdAt),
  ],
);

export const products = createTable("products", {
  id: uuid("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  name: text("name").notNull(),
  category: productCategoryEnum("category").notNull(),
  description: text("description"),
  // stored in sen (RM cents) to avoid floating point issues
  priceSen: integer("price_sen").notNull(),
  stock: integer("stock").notNull().default(0),
  imageUrl: text("image_url"),
  active: boolean("active").notNull().default(true),
  createdBy: text("created_by").references(() => user.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const orders = createTable(
  "orders",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    orderNo: text("order_no").notNull().unique(),
    customerName: text("customer_name").notNull(),
    customerPhone: text("customer_phone").notNull(),
    customerEmail: text("customer_email").notNull(),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "restrict" }),
    quantity: integer("quantity").notNull().default(1),
    unitPriceSen: integer("unit_price_sen").notNull(),
    totalSen: integer("total_sen").notNull(),
    status: orderStatusEnum("status").notNull().default("pending"),
    paymentMethod: paymentMethodEnum("payment_method"),
    paymentProofUrl: text("payment_proof_url"),
    billplzBillId: text("billplz_bill_id"),
    paymentVerifiedBy: text("payment_verified_by").references(() => user.id, {
      onDelete: "set null",
    }),
    paymentVerifiedAt: timestamp("payment_verified_at", {
      withTimezone: true,
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("gasak_orders_product_idx").on(t.productId)],
);

// ---------------------------------------------------------------------------
// Relations
// ---------------------------------------------------------------------------

export const userRelations = relations(user, ({ one, many }) => ({
  sessions: many(session),
  accounts: many(account),
  profile: one(playerProfiles, {
    fields: [user.id],
    references: [playerProfiles.userId],
  }),
  memberships: many(squadMembers),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

export const playerProfileRelations = relations(playerProfiles, ({ one }) => ({
  user: one(user, { fields: [playerProfiles.userId], references: [user.id] }),
}));

export const squadRelations = relations(squads, ({ many }) => ({
  members: many(squadMembers),
  events: many(events),
  scrims: many(scrims),
  tournaments: many(tournaments),
  announcements: many(announcements),
}));

export const squadMemberRelations = relations(squadMembers, ({ one }) => ({
  squad: one(squads, {
    fields: [squadMembers.squadId],
    references: [squads.id],
  }),
  user: one(user, { fields: [squadMembers.userId], references: [user.id] }),
}));

export const applicationRelations = relations(applications, ({ one }) => ({
  assignedLeader: one(user, {
    fields: [applications.assignedLeaderId],
    references: [user.id],
  }),
}));

export const eventRelations = relations(events, ({ one }) => ({
  squad: one(squads, { fields: [events.squadId], references: [squads.id] }),
  creator: one(user, { fields: [events.createdBy], references: [user.id] }),
}));

export const tournamentRelations = relations(tournaments, ({ one }) => ({
  squad: one(squads, {
    fields: [tournaments.squadId],
    references: [squads.id],
  }),
}));

export const scrimRelations = relations(scrims, ({ one }) => ({
  squad: one(squads, { fields: [scrims.squadId], references: [squads.id] }),
}));

export const announcementRelations = relations(
  announcements,
  ({ one, many }) => ({
    squad: one(squads, {
      fields: [announcements.squadId],
      references: [squads.id],
    }),
    author: one(user, {
      fields: [announcements.authorId],
      references: [user.id],
    }),
    reads: many(announcementReads),
  }),
);

export const announcementReadRelations = relations(
  announcementReads,
  ({ one }) => ({
    announcement: one(announcements, {
      fields: [announcementReads.announcementId],
      references: [announcements.id],
    }),
    user: one(user, {
      fields: [announcementReads.userId],
      references: [user.id],
    }),
  }),
);

export const productRelations = relations(products, ({ many }) => ({
  orders: many(orders),
}));

export const orderRelations = relations(orders, ({ one }) => ({
  product: one(products, {
    fields: [orders.productId],
    references: [products.id],
  }),
  verifier: one(user, {
    fields: [orders.paymentVerifiedBy],
    references: [user.id],
  }),
}));

export const activityLogRelations = relations(activityLogs, ({ one }) => ({
  actor: one(user, { fields: [activityLogs.actorId], references: [user.id] }),
}));

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type User = typeof user.$inferSelect;
export type PlayerProfile = typeof playerProfiles.$inferSelect;
export type Squad = typeof squads.$inferSelect;
export type SquadMember = typeof squadMembers.$inferSelect;
export type Application = typeof applications.$inferSelect;
export type Event = typeof events.$inferSelect;
export type Tournament = typeof tournaments.$inferSelect;
export type Scrim = typeof scrims.$inferSelect;
export type Announcement = typeof announcements.$inferSelect;
export type AnnouncementRead = typeof announcementReads.$inferSelect;
export type AuthSlide = typeof authSlides.$inferSelect;
export type ActivityLog = typeof activityLogs.$inferSelect;
export type Product = typeof products.$inferSelect;
export type Order = typeof orders.$inferSelect;

export type Lane = (typeof laneEnum.enumValues)[number];
export type SquadRole = (typeof squadRoleEnum.enumValues)[number];
export type ApplicationStatus =
  (typeof applicationStatusEnum.enumValues)[number];
export type EventType = (typeof eventTypeEnum.enumValues)[number];
export type ProductCategory = (typeof productCategoryEnum.enumValues)[number];
export type OrderStatus = (typeof orderStatusEnum.enumValues)[number];
export type PaymentMethod = (typeof paymentMethodEnum.enumValues)[number];
