import { generateId } from "@lib/id";
import type { MlbbRank } from "@lib/ranks";
import { relations } from "drizzle-orm";
import {
  boolean,
  foreignKey,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  pgTableCreator,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// Roles (stored as text on the Better Auth user table)
// ---------------------------------------------------------------------------

export const ORG_ROLES = ["admin", "seller", "user"] as const;
export type OrgRole = (typeof ORG_ROLES)[number];

// ---------------------------------------------------------------------------
// Multi-project schema pattern (t3 stack): every GASAK-owned table is
// prefixed so this DB can be shared with other projects. Better Auth's own
// tables below are named as its adapter expects and are left unprefixed.
// ---------------------------------------------------------------------------

export const createTable = pgTableCreator((name) => `gasak_${name}`);

// ---------------------------------------------------------------------------
// Better Auth tables (generated by @better-auth/cli)
// ---------------------------------------------------------------------------

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
  role: text("role"),
  banned: boolean("banned").default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
  mustChangePassword: boolean("must_change_password").notNull().default(false),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    impersonatedBy: text("impersonated_by"),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

// ---------------------------------------------------------------------------
// Domain enums
// ---------------------------------------------------------------------------

export const laneEnum = pgEnum("lane", [
  "exp",
  "jungle",
  "mid",
  "gold",
  "roam",
  "flex",
]);

export const squadRoleEnum = pgEnum("squad_role", [
  "leader",
  "coach",
  "player",
  "reserve",
]);

export const applicationStatusEnum = pgEnum("application_status", [
  "applied",
  "under_review",
  "trial",
  "accepted",
  "rejected",
]);

export const eventTypeEnum = pgEnum("event_type", [
  "practice",
  "tournament",
  "meeting",
  "scrim",
]);

export const productCategoryEnum = pgEnum("product_category", [
  "diamonds",
  "weekly_pass",
  "joki",
  "coaching",
]);

export const orderStatusEnum = pgEnum("order_status", [
  "pending",
  "waiting_payment",
  "paid",
  "processing",
  "completed",
  "cancelled",
]);

export const paymentMethodEnum = pgEnum("payment_method", [
  "duitnow_qr",
  "bank_transfer",
  "fpx",
  "billplz",
]);

export const tournamentFormatEnum = pgEnum("tournament_format", [
  "single_elimination",
  "double_elimination",
  "round_robin",
  "swiss",
  "other",
]);

export const tournamentStatusEnum = pgEnum("tournament_status", [
  "upcoming",
  "ongoing",
  "completed",
  "cancelled",
]);

export const matchOutcomeEnum = pgEnum("match_outcome", [
  "win",
  "loss",
  "draw",
  "pending",
]);

// Set once at creation and immutable afterward — determines whether the
// tournament exposes the Challonge connect/sync panel at all.
export const tournamentTrackingEnum = pgEnum("tournament_tracking", [
  "manual",
  "challonge",
]);

// ---------------------------------------------------------------------------
// Domain tables
// ---------------------------------------------------------------------------

export const playerProfiles = createTable("player_profiles", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  fullName: text("full_name"),
  nickname: text("nickname"),
  ign: text("ign"),
  mlbbId: text("mlbb_id"),
  serverId: text("server_id"),
  phone: text("phone"),
  preferredLanes: laneEnum("preferred_lanes").array(),
  currentRank: jsonb("current_rank").$type<MlbbRank>(),
  peakRank: jsonb("peak_rank").$type<MlbbRank>(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const squads = createTable("squads", {
  id: uuid("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  name: text("name").notNull(),
  description: text("description"),
  logoUrl: text("logo_url"),
  bannerUrl: text("banner_url"),
  // Optional hex accent color (e.g. #d97b16); falls back to the app-wide gold
  accentColor: text("accent_color"),
  recruiting: boolean("recruiting").notNull().default(false),
  archived: boolean("archived").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const squadMembers = createTable(
  "squad_members",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    squadId: uuid("squad_id")
      .notNull()
      .references(() => squads.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    squadRole: squadRoleEnum("squad_role").notNull().default("player"),
    joinedAt: timestamp("joined_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("gasak_squad_members_squad_user_idx").on(t.squadId, t.userId),
  ],
);

export const applications = createTable("applications", {
  id: uuid("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  fullName: text("full_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  ign: text("ign").notNull(),
  mlbbId: text("mlbb_id").notNull(),
  serverId: text("server_id").notNull(),
  currentRank: jsonb("current_rank").$type<MlbbRank>().notNull(),
  preferredLanes: laneEnum("preferred_lanes").array().notNull(),
  heroPool: text("hero_pool").notNull(),
  previousTeam: text("previous_team"),
  introduction: text("introduction").notNull(),
  squadId: uuid("squad_id").references(() => squads.id, {
    onDelete: "set null",
  }),
  status: applicationStatusEnum("status").notNull().default("applied"),
  assignedLeaderId: text("assigned_leader_id").references(() => user.id, {
    onDelete: "set null",
  }),
  reviewNotes: text("review_notes"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const events = createTable(
  "events",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    title: text("title").notNull(),
    description: text("description"),
    type: eventTypeEnum("type").notNull().default("practice"),
    startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
    endsAt: timestamp("ends_at", { withTimezone: true }),
    location: text("location"),
    // null squadId means an org-wide event
    squadId: uuid("squad_id").references(() => squads.id, {
      onDelete: "cascade",
    }),
    createdBy: text("created_by").references(() => user.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("gasak_events_squad_idx").on(t.squadId)],
);

export const tournaments = createTable(
  "tournaments",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    name: text("name").notNull(),
    organizer: text("organizer"),
    date: timestamp("date", { withTimezone: true }).notNull(),
    prize: text("prize"),
    // Final standing, freeform: "Champion", "Top 4", "Eliminated R2"
    placement: text("placement"),
    mvp: text("mvp"),
    screenshotUrl: text("screenshot_url"),
    format: tournamentFormatEnum("format")
      .notNull()
      .default("single_elimination"),
    status: tournamentStatusEnum("status").notNull().default("upcoming"),
    tracking: tournamentTrackingEnum("tracking").notNull().default("manual"),
    challongeTournamentId: text("challonge_tournament_id"),
    // Which Challonge participant is our squad (needed to filter matches)
    challongeParticipantId: text("challonge_participant_id"),
    challongeUrl: text("challonge_url"),
    lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
    squadId: uuid("squad_id").references(() => squads.id, {
      onDelete: "cascade",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("gasak_tournaments_squad_idx").on(t.squadId)],
);

export const tournamentRounds = createTable(
  "tournament_rounds",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    tournamentId: uuid("tournament_id")
      .notNull()
      .references(() => tournaments.id, { onDelete: "cascade" }),
    // Freeform: "Round 1", "Winners Semifinal", "Grand Final"
    roundLabel: text("round_label").notNull(),
    sortOrder: integer("sort_order").notNull().default(0),
    opponent: text("opponent").notNull(),
    scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
    eventId: uuid("event_id").references(() => events.id, {
      onDelete: "set null",
    }),
    outcome: matchOutcomeEnum("outcome").notNull().default("pending"),
    score: text("score"),
    notes: text("notes"),
    replayLink: text("replay_link"),
    // Set when synced from Challonge; used to upsert on re-sync
    challongeMatchId: text("challonge_match_id"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("gasak_tournament_rounds_tournament_idx").on(t.tournamentId),
    index("gasak_tournament_rounds_event_idx").on(t.eventId),
  ],
);

export const scrims = createTable(
  "scrims",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    squadId: uuid("squad_id")
      .notNull()
      .references(() => squads.id, { onDelete: "cascade" }),
    opponent: text("opponent").notNull(),
    date: timestamp("date", { withTimezone: true }).notNull(),
    result: text("result"),
    notes: text("notes"),
    replayLink: text("replay_link"),
    eventId: uuid("event_id").references(() => events.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("gasak_scrims_squad_idx").on(t.squadId),
    index("gasak_scrims_event_idx").on(t.eventId),
  ],
);

export const news = createTable(
  "news",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    title: text("title").notNull(),
    content: text("content").notNull(),
    // null squadId means global news
    squadId: uuid("squad_id").references(() => squads.id, {
      onDelete: "cascade",
    }),
    authorId: text("author_id").references(() => user.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("gasak_news_squad_idx").on(t.squadId)],
);

export const newsReads = createTable(
  "news_reads",
  {
    newsId: uuid("news_id")
      .notNull()
      .references(() => news.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    readAt: timestamp("read_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("gasak_news_reads_news_user_idx").on(t.newsId, t.userId)],
);

export const authSlides = createTable("auth_slides", {
  id: uuid("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  title: text("title").notNull(),
  description: text("description").notNull(),
  eyebrow: text("eyebrow").notNull().default("GASAK Management"),
  imageUrl: text("image_url").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const organizationPositions = createTable(
  "organization_positions",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    title: text("title").notNull(),
    icon: text("icon"),
    sortOrder: integer("sort_order").notNull().default(0),
    userId: text("user_id").references(() => user.id, {
      onDelete: "set null",
    }),
    parentId: uuid("parent_id"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    foreignKey({
      columns: [t.parentId],
      foreignColumns: [t.id],
      name: "gasak_organization_positions_parent_fk",
    }).onDelete("set null"),
    uniqueIndex("gasak_organization_positions_user_idx").on(t.userId),
  ],
);

export const activityLogs = createTable(
  "activity_logs",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    actorId: text("actor_id").references(() => user.id, {
      onDelete: "set null",
    }),
    actorName: text("actor_name"),
    actorEmail: text("actor_email"),
    actorRole: text("actor_role"),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id"),
    description: text("description").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("gasak_activity_logs_actor_idx").on(t.actorId),
    index("gasak_activity_logs_entity_idx").on(t.entityType, t.entityId),
    index("gasak_activity_logs_created_at_idx").on(t.createdAt),
  ],
);

export const products = createTable("products", {
  id: uuid("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  name: text("name").notNull(),
  category: productCategoryEnum("category").notNull(),
  description: text("description"),
  // stored in sen (RM cents) to avoid floating point issues
  priceSen: integer("price_sen").notNull(),
  stock: integer("stock").notNull().default(0),
  imageUrl: text("image_url"),
  active: boolean("active").notNull().default(true),
  // When true, price/stock/checkout are driven by productVariants instead of
  // this row's own priceSen/stock — those become a "starting from" display.
  hasVariants: boolean("has_variants").notNull().default(false),
  createdBy: text("created_by").references(() => user.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// An option group for a product, e.g. "Size" or "Color" (max 2 per product,
// enforced in the action layer — Shopee-style variant matrix).
export const productOptions = createTable(
  "product_options",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    sortOrder: integer("sort_order").notNull().default(0),
  },
  (t) => [index("gasak_product_options_product_idx").on(t.productId)],
);

// A single selectable value within an option group, e.g. "Red" under "Color".
export const productOptionValues = createTable(
  "product_option_values",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    optionId: uuid("option_id")
      .notNull()
      .references(() => productOptions.id, { onDelete: "cascade" }),
    value: text("value").notNull(),
    sortOrder: integer("sort_order").notNull().default(0),
  },
  (t) => [index("gasak_product_option_values_option_idx").on(t.optionId)],
);

// A concrete, orderable combination of option values (e.g. Red + M), with its
// own price/stock/image — this is what actually gets ordered.
export const productVariants = createTable(
  "product_variants",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    sku: text("sku"),
    priceSen: integer("price_sen").notNull(),
    stock: integer("stock").notNull().default(0),
    imageUrl: text("image_url"),
    active: boolean("active").notNull().default(true),
  },
  (t) => [index("gasak_product_variants_product_idx").on(t.productId)],
);

// Join table: which option values make up a given variant.
export const productVariantOptionValues = createTable(
  "product_variant_option_values",
  {
    variantId: uuid("variant_id")
      .notNull()
      .references(() => productVariants.id, { onDelete: "cascade" }),
    optionValueId: uuid("option_value_id")
      .notNull()
      .references(() => productOptionValues.id, { onDelete: "cascade" }),
  },
  (t) => [
    uniqueIndex("gasak_variant_option_values_idx").on(
      t.variantId,
      t.optionValueId,
    ),
  ],
);

export const orders = createTable(
  "orders",
  {
    id: uuid("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    orderNo: text("order_no").notNull().unique(),
    customerName: text("customer_name").notNull(),
    customerPhone: text("customer_phone").notNull(),
    customerEmail: text("customer_email").notNull(),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "restrict" }),
    variantId: uuid("variant_id").references(() => productVariants.id, {
      onDelete: "restrict",
    }),
    quantity: integer("quantity").notNull().default(1),
    unitPriceSen: integer("unit_price_sen").notNull(),
    totalSen: integer("total_sen").notNull(),
    status: orderStatusEnum("status").notNull().default("pending"),
    paymentMethod: paymentMethodEnum("payment_method"),
    paymentProofUrl: text("payment_proof_url"),
    billplzBillId: text("billplz_bill_id"),
    paymentVerifiedBy: text("payment_verified_by").references(() => user.id, {
      onDelete: "set null",
    }),
    paymentVerifiedAt: timestamp("payment_verified_at", {
      withTimezone: true,
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index("gasak_orders_product_idx").on(t.productId)],
);

// ---------------------------------------------------------------------------
// Relations
// ---------------------------------------------------------------------------

export const userRelations = relations(user, ({ one, many }) => ({
  sessions: many(session),
  accounts: many(account),
  profile: one(playerProfiles, {
    fields: [user.id],
    references: [playerProfiles.userId],
  }),
  memberships: many(squadMembers),
  organizationPositions: many(organizationPositions),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

export const playerProfileRelations = relations(playerProfiles, ({ one }) => ({
  user: one(user, { fields: [playerProfiles.userId], references: [user.id] }),
}));

export const squadRelations = relations(squads, ({ many }) => ({
  members: many(squadMembers),
  events: many(events),
  scrims: many(scrims),
  tournaments: many(tournaments),
  news: many(news),
}));

export const squadMemberRelations = relations(squadMembers, ({ one }) => ({
  squad: one(squads, {
    fields: [squadMembers.squadId],
    references: [squads.id],
  }),
  user: one(user, { fields: [squadMembers.userId], references: [user.id] }),
}));

export const organizationPositionRelations = relations(
  organizationPositions,
  ({ one, many }) => ({
    user: one(user, {
      fields: [organizationPositions.userId],
      references: [user.id],
    }),
    parent: one(organizationPositions, {
      fields: [organizationPositions.parentId],
      references: [organizationPositions.id],
      relationName: "organizationPositionChildren",
    }),
    children: many(organizationPositions, {
      relationName: "organizationPositionChildren",
    }),
  }),
);

export const applicationRelations = relations(applications, ({ one }) => ({
  assignedLeader: one(user, {
    fields: [applications.assignedLeaderId],
    references: [user.id],
  }),
  squad: one(squads, {
    fields: [applications.squadId],
    references: [squads.id],
  }),
}));

export const eventRelations = relations(events, ({ one }) => ({
  squad: one(squads, { fields: [events.squadId], references: [squads.id] }),
  creator: one(user, { fields: [events.createdBy], references: [user.id] }),
}));

export const tournamentRelations = relations(tournaments, ({ one, many }) => ({
  squad: one(squads, {
    fields: [tournaments.squadId],
    references: [squads.id],
  }),
  rounds: many(tournamentRounds),
}));

export const tournamentRoundRelations = relations(
  tournamentRounds,
  ({ one }) => ({
    tournament: one(tournaments, {
      fields: [tournamentRounds.tournamentId],
      references: [tournaments.id],
    }),
    event: one(events, {
      fields: [tournamentRounds.eventId],
      references: [events.id],
    }),
  }),
);

export const scrimRelations = relations(scrims, ({ one }) => ({
  squad: one(squads, { fields: [scrims.squadId], references: [squads.id] }),
  event: one(events, { fields: [scrims.eventId], references: [events.id] }),
}));

export const newsRelations = relations(news, ({ one, many }) => ({
  squad: one(squads, {
    fields: [news.squadId],
    references: [squads.id],
  }),
  author: one(user, {
    fields: [news.authorId],
    references: [user.id],
  }),
  reads: many(newsReads),
}));

export const newsReadRelations = relations(newsReads, ({ one }) => ({
  news: one(news, {
    fields: [newsReads.newsId],
    references: [news.id],
  }),
  user: one(user, {
    fields: [newsReads.userId],
    references: [user.id],
  }),
}));

export const productRelations = relations(products, ({ many }) => ({
  orders: many(orders),
  options: many(productOptions),
  variants: many(productVariants),
}));

export const productOptionRelations = relations(
  productOptions,
  ({ one, many }) => ({
    product: one(products, {
      fields: [productOptions.productId],
      references: [products.id],
    }),
    values: many(productOptionValues),
  }),
);

export const productOptionValueRelations = relations(
  productOptionValues,
  ({ one, many }) => ({
    option: one(productOptions, {
      fields: [productOptionValues.optionId],
      references: [productOptions.id],
    }),
    variantLinks: many(productVariantOptionValues),
  }),
);

export const productVariantRelations = relations(
  productVariants,
  ({ one, many }) => ({
    product: one(products, {
      fields: [productVariants.productId],
      references: [products.id],
    }),
    optionValues: many(productVariantOptionValues),
    orders: many(orders),
  }),
);

export const productVariantOptionValueRelations = relations(
  productVariantOptionValues,
  ({ one }) => ({
    variant: one(productVariants, {
      fields: [productVariantOptionValues.variantId],
      references: [productVariants.id],
    }),
    optionValue: one(productOptionValues, {
      fields: [productVariantOptionValues.optionValueId],
      references: [productOptionValues.id],
    }),
  }),
);

export const orderRelations = relations(orders, ({ one }) => ({
  product: one(products, {
    fields: [orders.productId],
    references: [products.id],
  }),
  variant: one(productVariants, {
    fields: [orders.variantId],
    references: [productVariants.id],
  }),
  verifier: one(user, {
    fields: [orders.paymentVerifiedBy],
    references: [user.id],
  }),
}));

export const activityLogRelations = relations(activityLogs, ({ one }) => ({
  actor: one(user, { fields: [activityLogs.actorId], references: [user.id] }),
}));

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type User = typeof user.$inferSelect;
export type PlayerProfile = typeof playerProfiles.$inferSelect;
export type Squad = typeof squads.$inferSelect;
export type SquadMember = typeof squadMembers.$inferSelect;
export type Application = typeof applications.$inferSelect;
export type Event = typeof events.$inferSelect;
export type Tournament = typeof tournaments.$inferSelect;
export type TournamentRound = typeof tournamentRounds.$inferSelect;
export type Scrim = typeof scrims.$inferSelect;
export type News = typeof news.$inferSelect;
export type NewsRead = typeof newsReads.$inferSelect;
export type AuthSlide = typeof authSlides.$inferSelect;
export type OrganizationPosition = typeof organizationPositions.$inferSelect;
export type ActivityLog = typeof activityLogs.$inferSelect;
export type Product = typeof products.$inferSelect;
export type ProductOption = typeof productOptions.$inferSelect;
export type ProductOptionValue = typeof productOptionValues.$inferSelect;
export type ProductVariant = typeof productVariants.$inferSelect;
export type Order = typeof orders.$inferSelect;

export type Lane = (typeof laneEnum.enumValues)[number];
export type SquadRole = (typeof squadRoleEnum.enumValues)[number];
export type ApplicationStatus =
  (typeof applicationStatusEnum.enumValues)[number];
export type EventType = (typeof eventTypeEnum.enumValues)[number];
export type TournamentFormat = (typeof tournamentFormatEnum.enumValues)[number];
export type TournamentStatus = (typeof tournamentStatusEnum.enumValues)[number];
export type MatchOutcome = (typeof matchOutcomeEnum.enumValues)[number];
export type TournamentTracking =
  (typeof tournamentTrackingEnum.enumValues)[number];
export type ProductCategory = (typeof productCategoryEnum.enumValues)[number];
export type OrderStatus = (typeof orderStatusEnum.enumValues)[number];
export type PaymentMethod = (typeof paymentMethodEnum.enumValues)[number];
