"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";
import _auth_slides from "./auth-slides.bones.json";
import _home_admin from "./home-admin.bones.json";
import _home_seller from "./home-seller.bones.json";
import _home_squad from "./home-squad.bones.json";
import _logs from "./logs.bones.json";
import _matches from "./matches.bones.json";
import _matches_detail from "./matches-detail.bones.json";
import _my_squad from "./my-squad.bones.json";
import _news from "./news.bones.json";
import _news_detail from "./news-detail.bones.json";
import _orders from "./orders.bones.json";
import _organization from "./organization.bones.json";
import _players from "./players.bones.json";
import _players_detail from "./players-detail.bones.json";
import _products from "./products.bones.json";
import _products_detail from "./products-detail.bones.json";
import _profile from "./profile.bones.json";
import _recruitment from "./recruitment.bones.json";
import _reports from "./reports.bones.json";
import _schedules from "./schedules.bones.json";
import _schedules_detail from "./schedules-detail.bones.json";
import _settings from "./settings.bones.json";
import _squads from "./squads.bones.json";
import _squads_detail from "./squads-detail.bones.json";
import _tournaments from "./tournaments.bones.json";
import _tournaments_detail from "./tournaments-detail.bones.json";
import _users from "./users.bones.json";

registerBones({
  "my-squad": _my_squad,
  "auth-slides": _auth_slides,
  "home-admin": _home_admin,
  "home-seller": _home_seller,
  "home-squad": _home_squad,
  logs: _logs,
  "matches-detail": _matches_detail,
  matches: _matches,
  "news-detail": _news_detail,
  news: _news,
  orders: _orders,
  organization: _organization,
  "players-detail": _players_detail,
  players: _players,
  "products-detail": _products_detail,
  products: _products,
  profile: _profile,
  recruitment: _recruitment,
  reports: _reports,
  "schedules-detail": _schedules_detail,
  schedules: _schedules,
  settings: _settings,
  "squads-detail": _squads_detail,
  squads: _squads,
  "tournaments-detail": _tournaments_detail,
  tournaments: _tournaments,
  users: _users,
});
