"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";
import _about from "./about.bones.json";
import _auth_images from "./auth-images.bones.json";
import _contact from "./contact.bones.json";
import _home from "./home.bones.json";
import _home_admin from "./home-admin.bones.json";
import _home_seller from "./home-seller.bones.json";
import _home_squad from "./home-squad.bones.json";
import _logs from "./logs.bones.json";
import _matches from "./matches.bones.json";
import _matches_detail from "./matches-detail.bones.json";
import _my_squad from "./my-squad.bones.json";
import _news from "./news.bones.json";
import _news_detail from "./news-detail.bones.json";
import _news_public from "./news-public.bones.json";
import _news_public_detail from "./news-public-detail.bones.json";
import _orders from "./orders.bones.json";
import _organization from "./organization.bones.json";
import _organization_public from "./organization-public.bones.json";
import _players from "./players.bones.json";
import _players_detail from "./players-detail.bones.json";
import _products from "./products.bones.json";
import _products_detail from "./products-detail.bones.json";
import _profile from "./profile.bones.json";
import _recruitment from "./recruitment.bones.json";
import _recruitment_public from "./recruitment-public.bones.json";
import _reports from "./reports.bones.json";
import _schedules from "./schedules.bones.json";
import _schedules_detail from "./schedules-detail.bones.json";
import _settings from "./settings.bones.json";
import _shop_order from "./shop-order.bones.json";
import _shop_public from "./shop-public.bones.json";
import _shop_public_detail from "./shop-public-detail.bones.json";
import _squads from "./squads.bones.json";
import _squads_detail from "./squads-detail.bones.json";
import _squads_public from "./squads-public.bones.json";
import _squads_public_detail from "./squads-public-detail.bones.json";
import _tournaments from "./tournaments.bones.json";
import _tournaments_detail from "./tournaments-detail.bones.json";
import _tournaments_public from "./tournaments-public.bones.json";
import _users from "./users.bones.json";

registerBones({
  "shop-order": _shop_order,
  about: _about,
  "auth-images": _auth_images,
  contact: _contact,
  "home-admin": _home_admin,
  "home-seller": _home_seller,
  "home-squad": _home_squad,
  home: _home,
  logs: _logs,
  "matches-detail": _matches_detail,
  matches: _matches,
  "my-squad": _my_squad,
  "news-detail": _news_detail,
  "news-public-detail": _news_public_detail,
  "news-public": _news_public,
  news: _news,
  orders: _orders,
  "organization-public": _organization_public,
  organization: _organization,
  "players-detail": _players_detail,
  players: _players,
  "products-detail": _products_detail,
  products: _products,
  profile: _profile,
  "recruitment-public": _recruitment_public,
  recruitment: _recruitment,
  reports: _reports,
  "schedules-detail": _schedules_detail,
  schedules: _schedules,
  settings: _settings,
  "shop-public-detail": _shop_public_detail,
  "shop-public": _shop_public,
  "squads-detail": _squads_detail,
  "squads-public-detail": _squads_public_detail,
  "squads-public": _squads_public,
  squads: _squads,
  "tournaments-detail": _tournaments_detail,
  "tournaments-public": _tournaments_public,
  tournaments: _tournaments,
  users: _users,
});
