"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";
import { configureBoneyard } from "boneyard-js/react";

import _dashboard_home from "./dashboard-home.bones.json";

configureBoneyard({
  color: "#1a1a1a",
  darkColor: "#1a1a1a",
  animate: "shimmer",
});

registerBones({
  "dashboard-home": _dashboard_home,
});
